"""Guards for the committed `form_schemas/*.json` field maps.

A bad map fails silently in production: `resolve_fields` reports a field whose
`profile_path` resolves to nothing as `missing` rather than asking the user, so the PDF
prints blank and nobody finds out until an application is rejected. These tests hold
every committed map — hand-written or generated by `app.forms.generate` — to the same
validator the generator retries against.

Runs against the in-memory store (no services). Run directly or via pytest.
"""
import os
import sys

os.environ.pop("REDIS_URL", None)  # force the in-memory store fallback
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.forms import filler  # noqa: E402
from app.forms.extract import extract_fields  # noqa: E402
from app.forms.validate import validate_fields  # noqa: E402
from app.models import CareRecipient, Caregiver, CaseProfile, Household  # noqa: E402


def _mapped_form_ids() -> list[str]:
    ids: list[str] = []
    for fname in sorted(os.listdir(filler.SCHEMA_DIR)):
        if not fname.endswith(".json"):
            continue
        form_id = fname[:-5]
        if filler.load_schema(form_id).get("fields") and filler._get_pdf_path(form_id):
            ids.append(form_id)
    return ids


def _filled_profile() -> CaseProfile:
    """A profile with every intake-derived field set, as a completed intake leaves it."""
    return CaseProfile(
        id="case-form-maps",
        care_recipient=CareRecipient(
            name="Test Recipient",
            first_name="Test",
            last_name="Recipient",
            date_of_birth="1950-06-15",
            age=75,
            state="CA",
            street_address="1 Test Street",
            city="Los Angeles",
            county="Los Angeles",
            zip_code="90001",
            conditions=["Dementia"],
            veteran=True,
            insurance="medi-cal",
            current_benefits=["SSI"],
            care_needs=["Bathing or showering"],
        ),
        caregiver=Caregiver(
            name="Test Caregiver",
            first_name="Test",
            last_name="Caregiver",
            relationship="Adult child",
            employment_status="Employed full time",
            phone="555-0100",
            email="caregiver@example.com",
            address="CA 90001",
            street_address="2 Test Street",
            city="Los Angeles",
            state="CA",
            county="Los Angeles",
            zip_code="90001",
        ),
        household=Household(size=3, income_monthly=2500.0),
    )


def test_committed_maps_are_valid():
    """Field names must exist in the PDF and profile_paths must be fillable."""
    checked = 0
    for form_id in _mapped_form_ids():
        schema = filler.load_schema(form_id)
        pdf_fields = extract_fields(filler._get_pdf_path(form_id))
        problems = validate_fields(schema["fields"], pdf_fields)
        assert not problems, f"{form_id}:\n  " + "\n  ".join(problems)
        checked += 1
    assert checked > 0, "expected at least one mapped schema with a PDF to validate"


def test_mapped_fields_resolve_from_a_complete_profile():
    """Anything claiming a profile_path must actually produce a value."""
    profile = _filled_profile()
    for form_id in _mapped_form_ids():
        schema = filler.load_schema(form_id)
        result = filler.resolve_fields(form_id, profile)
        claimed = {
            name
            for name, spec in schema["fields"].items()
            if isinstance(spec, dict) and spec.get("profile_path")
        }
        # check_when fields legitimately resolve to nothing when the condition is unmet.
        conditional = {
            name
            for name, spec in schema["fields"].items()
            if isinstance(spec, dict) and "check_when" in spec
        }
        blank = sorted(claimed - conditional - set(result["resolved"]))
        assert not blank, (
            f"{form_id}: mapped to a profile_path but empty for a fully populated "
            f"profile, so the PDF prints blank and the user is never asked: {blank}"
        )


def test_every_mapped_form_still_fills():
    """The end product: each form renders to a PDF with its values written in."""
    profile = _filled_profile()
    for form_id in _mapped_form_ids():
        pdf_bytes = filler.fill_pdf(form_id, profile)
        assert pdf_bytes.startswith(b"%PDF"), f"{form_id}: did not produce a PDF"
        assert len(pdf_bytes) > 1000, f"{form_id}: suspiciously small output"


if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failed = 0
    for t in tests:
        try:
            t()
            print(f"PASS {t.__name__}")
        except AssertionError as e:
            failed += 1
            print(f"FAIL {t.__name__}: {e}")
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    sys.exit(1 if failed else 0)
